parameters:
  - name: ansible_inventory_filepath
  - name: ansible_host
  - name: ansible_host_ssh_key_filename
  - name: ansible_username
  - name: ansible_playbook_filepath
  - name: display_name

steps:
  - bash: |
      set -e

      chmod 400 $(Agent.TempDirectory)/${{ parameters.ansible_host_ssh_key_filename }}

      ansible-playbook \
        --inventory ${{ parameters.ansible_inventory_filepath }} \
        --limit ${{ parameters.ansible_host }} \
        --user ${{ parameters.ansible_username }} \
        ${{ parameters.ansible_playbook_filepath }} \
        --extra-vars="ansible_ssh_private_key_file=$(Agent.TempDirectory)/${{ parameters.ansible_host_ssh_key_filename }}"
    displayName: ${{ parameters.display_name }}
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
