parameters:
  - name: stage
  - name: region
  - name: depends_on
    default: ''

stages:
  - stage: ${{ parameters.stage }}_deploy_app_hello_world_${{ parameters.region }}
    dependsOn: ${{ parameters.depends_on }}
    variables:
      - template: ../vars/vars-${{ parameters.stage }}.yml
    jobs:
      - template: ../jobs/deploy-hello-world-app.yml
        parameters:
          ansible_inventory_filepath: ansible/inventories/${{ parameters.stage }}/hosts
          ansible_host: docker_hosts_${{ parameters.region }}
          ansible_host_ssh_key_filename: ${{ variables.ansible_host_ssh_key_filename }}
          ansible_username: $(ansible_username)
          ansible_playbook_filepath: $(ansible_playbook_filepath_hello_world)
