parameters:
  - name: environment
  - name: region
  - name: depends_on
    default: ""
  - name: skip
    default: false

stages:
  - stage: ${{ parameters.environment }}_deploy_app_hello_world_${{ parameters.region }}
    dependsOn: ${{ parameters.depends_on }}
    condition: and(not(failed()), eq('${{ parameters.skip }}', 'false'))
    variables:
      - template: ../vars/vars-${{ parameters.environment }}.yml
    jobs:
      - template: ../jobs/deploy-hello-world-app.yml
        parameters:
          ansible_inventory_filepath: ansible/inventories/${{ parameters.environment }}/hosts
          ansible_host: docker_hosts_${{ parameters.region }}
          ansible_host_ssh_key_filename: ${{ variables.ansible_host_ssh_key_filename }}
          ansible_username: $(ansible_username)
          ansible_playbook_filepath: $(ansible_playbook_filepath_hello_world)
