parameters:
  - name: stage
  - name: region
  - name: depends_on
    default: []

stages:
  - stage: ${{ parameters.stage }}_tf_apply_${{ parameters.region }}
    dependsOn: ${{ parameters.depends_on }}
    variables:
      - template: ../vars/vars-${{ parameters.stage }}.yml
      - group: ${{ parameters.stage }}
    jobs:
      - template: ../jobs/tf-apply.yml
        parameters:
          environment: ${{ parameters.stage }}
          terraform_version: $(tf_version)
          service_principal_id: $(service_principal_id)
          service_principal_secret: $(service_principal_secret)
          tenant_id: $(tenant_id)
          subscription_id: $(subscription_id)
          storage_account_name: $(tf_storage_account_name)
          working_directory: terraform
          terraform_backend_config: -backend-config="../terraform/environments/$(environment)/tf-backend-${{ parameters.region }}.conf"
          terraform_parameters: -var-file="../terraform/environments/$(environment)/terraform-${{ parameters.region }}.tfvars"
