parameters:
  - name: stage
  - name: region

stages:
  - stage: ${{ parameters.stage }}_tf_apply_${{ parameters.region }}
    variables:
      - template: ../variables/${{ parameters.stage }}/common.yml
      - group: ${{ parameters.stage }}
    jobs:
      - template: ../jobs/tf-apply.yml
        parameters:
          environment: ${{ parameters.stage }}
          terraform_version: $(tf_version)
          service_principal_id: $(SERVICE_PRINCIPAL_ID)
          service_principal_secret: $(SERVICE_PRINCIPAL_SECRET)
          tenant_id: $(TENANT_ID)
          subscription_id: $(SUBSCRIPTION_ID)
          storage_account_name: $(tf_storage_account_name)
          working_directory: terraform
          terraform_backend_config: -backend-config="../terraform/environments/$(environment)/tf-backend-${{ parameters.region }}.conf"
          terraform_parameters: -var-file="../terraform/environments/$(environment)/terraform-${{ parameters.region }}.tfvars"
