parameters:
  - name: stage
  - name: environment
  - name: terraform_parameters
    default: ""
  - name: terraform_backend_config
  - name: working_directory

jobs:
  - deployment: terraform_apply
    variables:
    - template: ../vars/vars-${{ parameters.stage }}.yml
    - group: ${{ parameters.stage }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            # AZ Login
            - template: ../steps/az-login.yml

            # Terraform Apply
            - template: ../steps/tf-apply.yml
              parameters:
                working_directory: ${{ parameters.working_directory }}
                terraform_parameters: ${{ parameters.terraform_parameters }}
                terraform_backend_config: ${{ parameters.terraform_backend_config }}
