parameters:
  - name: stage
  - name: terraform_parameters
    default: ""
  - name: terraform_backend_config
  - name: working_directory

jobs:
  - job: terraform_plan
    variables:
    - template: ../vars/vars-${{ parameters.stage }}.yml
    - group: ${{ parameters.stage }}
    steps:
      # AZ Login
      - template: ../steps/az-login.yml

      # Terraform Plan
      - template: ../steps/tf-plan.yml
        parameters:
          working_directory: ${{ parameters.working_directory }}
          terraform_parameters: ${{ parameters.terraform_parameters }}
          terraform_backend_config: ${{ parameters.terraform_backend_config }}
