parameters:
  - name: stage
  - name: terraform_parameters
    default: ""
  - name: terraform_backend_config
  - name: working_directory

jobs:
  - job: terraform_plan
    variables:
    - template: ../vars/vars-${{ parameters.stage }}.yml
    - group: ${{ parameters.stage }}
    steps:
      # AZ Login
      - template: ../steps/az-login.yml
        parameters:
          service_principal_id: $(service_principal_id)
          service_principal_secret: $(service_principal_secret)
          tenant_id: $(tenant_id)
          subscription_id: $(subscription_id)

      # Terraform Plan
      - template: ../steps/tf-plan.yml
        parameters:
          service_principal_id: $(service_principal_id)
          service_principal_secret: $(service_principal_secret)
          subscription_id: $(subscription_id)
          tenant_id: $(tenant_id)
          storage_account_name: $(tf_storage_account_name)
          working_directory: ${{ parameters.working_directory }}
          terraform_version: $(tf_version)
          terraform_parameters: ${{ parameters.terraform_parameters }}
          terraform_backend_config: ${{ parameters.terraform_backend_config }}
